### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by b3nharris** [ds4owd-001/md-02-assignments-b3nharris#1]
Hi @larnsce @mianzg @sskorik01.

I've completed this assignment. No questions (I asked one about PATs in Element so others can see the answer). I added a few extra lines of code - for example to practice changing color schemes. Think I've done this right, but let me know if I've made errors in how I should be doing this.

And thanks for the course so far - it's been great!

**Comment by larnsce** [comment]
Thanks for the compliment, @b3nharris. We are happy that you enjoy the course.

Well done for working through the homework, and great that you are trying things out yourself. That's what will help you learn and transfer the knowledge. Your question on Element was also very helpful. If you do want to work locally with R, RStudio and Git, then have a look at the following link on how you can store your GitHub PAT (see `gitcreds::gitcreds_set()` as you already have a PAT): https://happygitwithr.com/https-pat#tldr

You can close the issue now.
